--- #YAML:1.0
name: Module-ParseDeps
version: 0.01
author: Robert Rothenberg <rrwo at cpan.org>
abstract: parse module dependencies from CPAN distribution
license: perl
requires:
  Carp: 0
  File::Spec: 0
  Module::MakefilePL::Parse: 0.03
  YAML: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.25
